# Generated by Django 3.2.9 on 2021-12-06 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_helper_project_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='learners',
            field=models.ManyToManyField(related_name='learning', through='teacher_helper_project_api.StudentMeeting', to='teacher_helper_project_api.Student'),
        ),
    ]
